# -*- coding: utf-8 -*-
class Locators():


    # Home page locators
    you_may_like_xpath = "//*[text()='You May Like']"
    Currency_select="//*[@class='search-enabled--true section header-top__margin']//*[@class='flags']/.."
    Currency_List_select="//*[@class='disclosure__button abc']"
    mega_menu_path = "//div[@class='main-nav__wrapper']/div/div[contains(@class,'mega-menu')]/div[@class='dropdown menu']/div/div/a[text()='{}']"
    search_textbox_xpath = "//div[@class='main-nav__wrapper']/div/div/form[@class='search__form']/input[@name='q']"
    home_button_xpath = "//*[@class='top-bar']//div[contains(@class,'logo')]/a[@title='Distacart']"
    judge_me_reviews_bottom_img="//*[@class='jdgm-carousel-item__product jdgm--shop-review-has-image']"
    judge_me_reviews_bottom_left_arrow="//*[@class='jdgm-carousel__left-arrow']"
    scrolled_down_home_button = "//*[@class='header__logo logo--image']"
    checkout_shipping_text="//*[contains(text(),'Shipping method')]"
    Explore_top_categories_xpath = "//div[@id='shopify-section-5dc533dc-2f11-4ac3-898a-6c76820d56f5']//h2[@class='title center']"
    top_categories_collections_xpath = "//div[@id='shopify-section-5dc533dc-2f11-4ac3-898a-6c76820d56f5']//div[@class='rte-setting']/p/a"

    shop_by_categories_xpath = "//div[@class='main-nav__wrapper']/div/div/ul/div/li/a[@data-dropdown-rel='shop-by-categories']"
    product_main_menu_xpath = "//div[@class='main-nav__wrapper']/div/div[contains(@class,'mega-menu')]//div/div/div/div/ul/li/a[text()='{}']"
    pick_currency_div_xpath = "//div[contains(@class,'selectors-form__currency')]/div/button"
    currency_select_id = "currencies"
    currency_select_xpath = "//div[contains(@class,'selectors-form__currency')]/div/div/ul/li/button[@value='{}']"
    currency_select_xpath_CS="//*[@class='search-enabled--true section header-top__margin']//*[@class='flags']/..//*[contains(text(),'{}')]"
    all_currencies="//div[contains(@class,'selectors-form__currency')]/div/div/ul/li/button"
    country_name_xpath="//*[@class='quick-links']"
    shipping_text_xpath="//*[@id='shipping_dtl']"
    login_register_xpath = "//a[@title='Login']/span[text()='Login']"
    referral_program="//*[text()='Referral program']"
    user_name_id = "customer_email"
    user_password_id = "customer_password"
    login_button_xpath = "//form[@id='customer_login']/input[@value='Login']"
    user_login_xpath = "//span[text()='Login']"
    referral_button_id = "rewardify-referral"
    my_account_xpath = "//div[@class='top-bar--right-menu']/ul/li/a/span[text()='My Account']"
    logout_xpath = "//span/a[@id='customer_logout_link']"
    browse_all_brands_xpath = "//*[text()='Browse All Brands']"
    all_brands_xpath = "//*[@class='brands-links']/li/a"
    currencies_list_xpath = "//div[contains(@class,'selectors-form__currency')]/div/div/ul/li/button"
    cart_popup_order_notes_xpath = "//input[@placeholder='Order Note']"
    cart_popup_checkout_xpath = "//button[@name='checkout']"
    cart_popup_total_xpath = "//div[@class='tos_warning cart_content animated fadeIn']//ul/li/span/span[@class='money']"
    cart_popup_item_price_xpath = "//ul[contains(@class,'cart_items js-cart_items')]/li[contains(@class,'mini-cart__item')]/div/div/strong/span[@class='money']"
    free_shipping_link_xpath = "//a/p[contains(text(),'Free Shipping')]"
    returns_policy_link_xpath = "//p/a[text()='Return Policy']"
    suggest_a_product_homepage = "//li/a[text()='Suggest a Product']"
    suggest_product_page_title ="//div/h1[text()='Suggest a Product']"
    suggest_product_page_element_cs = "//div/h5[text()='CONTACT US:']"
    suggest_a_product_page_element_name = "//div[text()='Name:']"
    send_button = "//input[@value='Send Message']"
    contact_us_link = "//li/a[text()='Contact Us']"
    contact_us_page_title = "//a[text()='Contact']"
    contact_us_page_email = "//a[text()='happy@distacart.com']"
    email_input_box = "//input[@type='email' ]"
    notify_me_via_email_button = "//button[@class='action_button sign_up']"
    currency_current_text_xpath="//*[@aria-controls='currency-list']"
    toll_free_text = "//div[@class='main-nav__wrapper']//div/span[text()='24/7 Toll Free:']/../a[@class='tollfree-number']"
    legal_policy_text = "//a[text()='Legal Policy']"
    Shop_Now_img_xpath = "//*[@class='product-wrap']/div/following-sibling::a"
    assert_shop_now_page="//*[@aria-current='page']"
    most_popular_section_xpath = "//*[text()='Most Popular Products']"
    trending_section_xpath = "//*[text()='Trending Products']"
    most_popular_section_add_to_cart_xpath = "//*[contains(text(),'Products')]/following-sibling::div/div/ul/li//*[text()='+ Add to cart']"
    most_popular_section_bg_color_xpath="//*[contains(text(),'Products')]/following-sibling::div/div/ul/li"
    most_popular_section_add_to_cart_color_xpath="//*[contains(text(),'Products')]/following-sibling::div/div/ul/li//*[text()='+ Add to cart']/.."
    most_popular_section_img_xpath="//*[contains(text(),'Products')]/following-sibling::div/div/ul/li//*[@class='ls-image']"
    most_popular_section_product_variants_xpath = "//*[@class='ls-select__text']"
    most_popular_section_product_title_xpath = "//*[contains(text(),'Products')]/following-sibling::div/div/ul/li//*[@class='ls-title']"
    most_popular_section_product_price_xpath = "//*[contains(text(),'Products')]/following-sibling::div/div/ul/li//*[@class='ls-price-wrap']/span[contains(@class,'ls-price money')]"
    most_popular_section_product_stars_xpath="//*[contains(text(),'Products')]/following-sibling::div/div/ul/li//*[@class='jdgm-prev-badge__stars']"
    most_popular_section_product_reviews_xpath="//*[@class='jdgm-star jdgm--on']/../..//*[@class='jdgm-prev-badge__text']"
    most_popular_section_product_questions_xpath="//*[contains(text(),'Products')]/following-sibling::div/div/ul/li//*[@class='jdgm-qa-badge__text']"
    you_may_like_add_to_cart_xpath = "//*[contains(text(),'You May')]/following-sibling::div/div/ul/li//*[text()='+ Add to cart']"
    you_may_like_product_title_xpath = "//*[contains(text(),'You May')]/following-sibling::div/div/ul/li"
    you_may_like_product_price_xpath = "//*[contains(text(),'You May')]/following-sibling::div/div/ul/li//*[@class='ls-price-wrap']/span[contains(@class,'ls-price money')]"
    you_may_like_product_stars_xpath = "//*[contains(text(),'You May')]/following-sibling::div/div/ul/li//*[@class='jdgm-prev-badge__stars']"
    you_may_like_product_reviews_xpath = "//*[contains(text(),'You May')]/following-sibling::div/div/ul/li//*[@class='jdgm-prev-badge__text']"
    you_may_like_product_questions_xpath = "//*[contains(text(),'You May')]/following-sibling::div/div/ul/li//*[@class='jdgm-qa-badge__text']"
    cart_popup_product_title_xpath = "//*[@class='item_title']/a"
    cart_popup_product_price_xpath = "//*[@class='money']"
    cart_popup_product_quantity_xpath = "//*[@class='quantity']"  # take the attribute of value to get the quantity
    cart_popup_product_remove_icon = "//*[@class='remove-icon']"
    cart_popup_close_button = "//*[@class='mini-cart-header']//*[@class='close_mini_cart']"
    cart_pop_up_fulfillment_error = "//*[text()='_fulfillments-count: 1 ']"
    all_elements_presented_on_collection_page_xpath = "//div[@class='pf-c']"
    click_on_search_xpath = "//div[@class='main-nav__wrapper']//div[@class='search-container']//input[@placeholder='Search']"

    # collection Page
    # comment
    collection_page_product_price_s="//*[@id='snize-search-results-grid-mode']/ul/li//*[@class='snize-price-list']/span"
    collection_page_product_add_to_cart_s="//*[@id='snize-search-results-grid-mode']/ul/li//*[contains(text(),'{}')]/..//*[text()='Quick view']"
    all_products_in_collection_page_title = "//*[@class='snize-title']"
    single_product_select_in_collection_page="//*[text()='{}']"
    please_select_other_variant_text_xpath="//*[text()='Please select another variant']"
    selected_varaint_is_sold_text_xpath="//*[text()='Selected Variant is Sold out']"
    single_product_add_tocart="//*[text()='{}']/../..//*[contains(text(),'+   Add to Cart')]"
    dista_pick_text_xpath="//*[text()='Dista Pick']/following-sibling::input/..//*[text()='Dista Pick']"
    option_select_collection_page="//*[@title='{}']/../../..//*[@class='selector-wrapper']/select/option[@value='{}']"
    discount_visibility = "//*[@class='snize-discount']"

    all_products_in_collection_page_img="//*[@class='product-list collection-matrix is-flex is-flex-wrap equal-columns--outside-trim']//*[contains(@class,'product-grid-box')]//*[@class='gallery-cell is-selected']/div/img"
    all_products_in_collection_page_prices = "//*[@class='product-list collection-matrix is-flex is-flex-wrap equal-columns--outside-trim']//*[contains(@class,'product-grid-box')]//*[contains(@class,'current_price')]"
    all_products_in_collection_page_add_to_cart = "//*[@class='product-list collection-matrix is-flex is-flex-wrap equal-columns--outside-trim']//*[contains(@class,'product-grid-box')]//*[contains(text(),'Add to cart')]"
    all_products_in_collection_page_add_to_cart_2nd_click = "//*[@class='product-list collection-matrix is-flex is-flex-wrap equal-columns--outside-trim']//*[contains(@class,'product-grid-box')]//div[@class='purchase-details__buttons purchase-details__spb--false ']/button[@name='add' and contains(@class,'ajax-submit') and contains(@style,'display:block')]/span"
    all_products_in_collection_page_add_to_cart_2nd_click_color="//*[@class='product-list collection-matrix is-flex is-flex-wrap equal-columns--outside-trim']//*[contains(@class,'product-grid-box')]//div[@class='purchase-details__buttons purchase-details__spb--false ']/button[@name='add' and contains(@class,'ajax-submit') and contains(@style,'display:block')]"
    all_products_in_collection_page_reviews="//*[@class='product-list collection-matrix is-flex is-flex-wrap equal-columns--outside-trim']//*[contains(@class,'product-grid-box')]//*[@class='jdgm-prev-badge__text']"
    all_products_in_collection_page_questions="//*[@class='product-list collection-matrix is-flex is-flex-wrap equal-columns--outside-trim']//*[contains(@class,'product-grid-box')]//*[@class='jdgm-qa-badge__text']"
    all_products_in_collection_page_star_badge="//*[@class='product-list collection-matrix is-flex is-flex-wrap equal-columns--outside-trim']//*[contains(@class,'product-grid-box')]//*[@class='jdgm-prev-badge__stars']"
    sort_by_collections_page="//*[@id='sort-by']"
    sort_by_featured="//*[@id='sort-by']/option[text()='Featured']"
    sort_by_best_selling="//*[@id='sort-by']/option[text()='Best Selling']"
    sort_by_Alpha_A_Z="//*[@id='sort-by']/option[text()='Alphabetically: A-Z']"
    sort_by_Alpha_Z_A="//*[@id='sort-by']/option[text()='Alphabetically: Z-A']"
    sort_by_price_L_H="//*[@id='sort-by']/option[text()='Price: Low to High']"
    sort_by_price_H_L="//*[@id='sort-by']/option[text()='Price: High to Low']"
    sort_by_Date_N_O="//*[@id='sort-by']/option[text()='Date: New to Old']"
    sort_by_Date_O_N="//*[@id='sort-by']/option[text()='Date: Old to New']"
    tile_xpath="//*[contains(@class,'product-grid-box ')]"
    quick_view_CC_xpath="//*[@class='cc-quick-btn']"
    fulfiller_link_xpath="//*[@class='wk_seller_detail clearfix pdp-page__text']/a"
    quick_view_title_xpath="//*[@class='cc-product-content']/a"
    fullcart_variant_xpath = "//h3[@class='cart__item--title']/a[text()='Patanjali Giloy Ghanvati - 60 tabs / Pack of 1']"
    discount_popup_xpath ="//button[text()='No Thanks']"
    #Schema Xpath
    product_select_schema="//*[text()='Product']"
    product_schema_count="//*[@class='mdl-list__item-primary-content']//*[text()='Product']"




    # comment
    # Full Cart Page
    top_recomendation_add_to_cart_button = "//*[@class='ls-li ls-no-overlay ls-show']//*[@class='ls-button ls-button--select ls-add-to-cart']"
    top_recomendation_product_title = "//*[@class='ls-message-param']"
    top_recomendation_product_price = "//*[@class='ls-message-param money']"
    full_cart_item_title = "//*[@class='cart__item--title']"
    full_cart_item_price = "//*[text()='Total:']/following-sibling::span"
    full_cart_remove_item = "//*[@data-remove-item='cart-template']"
    full_cart_quantity_edit="//input[@data-cart-quantity-input='cart-template']"


    # Cart slider locators
    cart_free_shipping_msg_xpath = "//p[@class='mini-shipping-msg']/span"
    cart_free_shipping_progress_bar_xpath = "//div[@class='cartProgressBarTxt']"
    cart_slider_quantity_plus_button_xpath = "//div[@class='left product-quantity-box']/span[contains(@class,'product-plus')]/span"
    cart_slider_quantity_minus_button_xpath = "//div[@class='left product-quantity-box']/span[contains(@class,'product-minus')]/span"
    cart_slider_product_shipping_info_xpath = "//span[@class='delivery_desc']"
    cart_close_button_xpath="//*[@class='mini-cart-header']//*[@class='close_mini_cart']"
    my_cart_button_xpath = "//*[@class='top-bar--right-menu']//*[@class='icon-bag mini_cart ']"
    max_quantity_msg_mini_cart_xpath="//*[@class='warning warning--quantity animated bounceIn']"
    delivery_time_xpath = "//p[@class='delivery_within_txt']/b[@class='delivery_time']"
    i_icon_xpath = "//p[@class='delivery_within_txt']/span[@class='delivery_tooltip']"
    order_with_in_xpath = "//p[@class='delivery_within_txt']"
    order_with_in_days_xpath = "//p[@class='delivery_within_txt']/b[@class='delivery_day']"

    # Product page locators
    product_title_xpath = "//h1[@class='product_name']"
    shipping_msg_mini_cart_xpath = "//*[@class='shipping-msg']"
    product_vendor_xpath = "//div[@class='vendor-box']/div[contains(@class,'wk_seller')]/a"
    product_fulfilled_xpath = "//div/span[contains(@class,'vendor_padding')]/a"
    dista_picks_label_xpath="//*[@class='product-labels-block']"
    best_seller_label_xpath="//*[@class='product-labels-block']"
    text_label_xpath="//*[@class='product-labels-block']"
    product_detail_star_badges_xpath = "//div[@class='prod-reviews']/div[contains(@class,'jdgm-widget')]/div/span[@class='jdgm-prev-badge__stars']"
    product_detail_stars_xpath = "//div[@class='prod-reviews']/div[contains(@class,'jdgm-widget')]/div/span[@class='jdgm-prev-badge__text']"
    product_detail_qa_icon_xpath = "//div[@class='one-half columns medium-down--one-whole product-section__right']/div/div/div/span[@class='jdgm-qa-badge ']"
    product_detail_qa_text_xpath = "//div[@class='one-half columns medium-down--one-whole product-section__right']/div[contains(@class,'jdgm-widget')]/div/span[@class='jdgm-qa-badge ']/span[@class='jdgm-qa-badge__text']"
    product_page_price_xpath = "//div[@class='modal_price']/div/span/span/span"
    product_not_available_xpath = "//div[@class='one-whole column']//strong"
    product_sold_out_xpath = "//div[@class='product_availability_check']/div/div/span[text()='Sold out']"
    product_notify_button_xpath = "//button[text()='Notify When Back in Stock']"
    product_questions_xpath="//*[@class='jdgm-qa-badge__text']"
    judge_me_questions_number="//*[text()='Questions (']//*[@class='jdgm-subtab__count']"
    product_variant_xpath = "//div[@value='{}']"
    product_notify_variant_xpath = "//div[@id='container']/form/div/div/select[@id='variants']"
    product_notify_email_xpath = "//input[@id='email']"
    product_notify_me_button_xpath = "//button[text()='Notify me when available']"
    product_page_sticky_add_to_cart = "//*[@class='ajax-submit action_button add_to_cart action_button--secondary product_add_to_cart']"
    product_page_sticky_title = "//*[@class='prod_title']"
    product_page_sticky_price = "//*[@class='current_price_div']/span//span[@class='money']"
    add_to_cart_product_page = "//*[@class=' purchase-details-product-addbtn1 ']/button"
    add_to_cart_not_available="//*[@class='purchase-details__buttons purchase-details__spb--true product-is-unavailable']"
    fastest_shipping_text_product_page_xpath = "//*[text()='*Based on fastest shipping method']"
    order_date_product_page_xpath = "//*[@class='order_date orderdate']"
    shipping_dates_product_page = "//*[@class='shipping_date shippingdate']"
    delivery_dates_product_page = "//*[@class='delivery_date deliverydate']"
    ready_to_ship_text_product_page = "//*[@class='pdp-page__text prod_del_info']"
    after_pay_price_xpath="//*[@class='afterpay_price']"
    after_pay_popup_xpath="//*[@class='afterpay-logo-badge-background']/../.."
    after_pay_logo_badge_xpath="//*[@class='afterpay_paragraph']"
    after_pay_popup_logo_xpath="//*[@class='afterpay-modal-logo afterpay_logo']"
    product_variant_of_pack_of_3_xpath="//*[@data-value='Pack of 3']"
    product_variant_of_pack_of_n_xpath="//*[@data-value='{}']"
    judge_me_text="//*[@class='jdgm-rev-widg__summary-text']"

    product_xpath = "//span[text()='{}']"
    product_available_xpath = "//*[@class='snize-overhidden']//*[contains(text(),'{}')]"
    product_soldout_xpath = "//a[contains(@href,'{}')]/div/span/div[contains(text(),'Sold')]/../../span[@class='title']"
    product_name_xpath = "//*[@class='snize-title']"
    product_category_title = "//*[text()='{}']"
    add_to_cart_button_xpath = "//div[@class='product_availability_check']//div[contains(@class,'purchase-details')]/div[contains(@class,'purchase-details-product-addbtn1')]/button/span[contains(text(),'Add to cart')]"
    # buy_it_now_button_xpath = "//span[contains(text(),'Buy with')]"
    buy_it_now_button_xpath="//*[contains(text(),'Buy it now')]"
    buy_with_shop_pay="//*[text()='Buy now with ShopPay']/.."
    continue_with_shop_pay="//*[text()='Continue with']"
    sold_out_button_xpath = "//div[@class='seven columns medium-down--one-whole  omega']/div[@class='product_availability_check']/p/span[text()='Sold Out']"
    quantity_plus_button_xpath = "//div[@class='one-half columns medium-down--one-whole product-section__right']//div[@class='purchase-details']/div[contains(@class,'purchase-details__quantity')]/span[contains(@class,'product-plus')]/span"
    quantity_minus_button_xpath = "//div[@class='one-half columns medium-down--one-whole product-section__right']//div[@class='purchase-details']/div[contains(@class,'purchase-details__quantity')]/span[contains(@class,'product-minus')]/span"
    load_more_button_xpath = "//span/a[contains(@class,'load-more__btn')]"
    buy_it_now_display_none_xpath = "//div[@class='shopify-payment-button' and @style='display: none;']"
    product_price_xpath = "//div[@class='one-half columns medium-down--one-whole product-section__right']/div/div[@class='modal_price']/div/span/span/span"
    added_button_xpath = "//button[@class='cbb-also-bought-add-to-cart-button']/span[text()='Added']"
    shipping_info_xpath = "//span[@class='pdp-page__text prod_del_info']"
    rapid_shipping_info_xpath = "//span[contains(@class,'rapiddelivery_info')]"
    rapid_label_xpath="//*[@class='rapiddelivery']"
    rapid_delivery_info_xpath="//*[@class='rapid_delivery_info']"
    rapid_delivery_pop_up_content_xpath="//*[@class='rapid_delivery-popup-content']/h2"
    quantity_input_xpath = "//div[@class='one-half columns medium-down--one-whole product-section__right']//div[@class='purchase-details']/div[contains(@class,'purchase-details__quantity')]/input[@id='quantity']"
    max_quantity_msg_xpath = "//div[@class='one-half columns medium-down--one-whole product-section__right']//p[@class='warning animated bounceIn']"
    notify_button_xpath = "//div[@class='seven columns medium-down--one-whole  omega']//div[@class='purchase-details']/div[contains(@class,'purchase-details__buttons')]/a[text()='Notify Me When Available']"
    notify_button_xpath1="//*[text()='Notify me when available']"
    homepage_shipping_link = "//*[contains(text(),'Free Shipping & Returns & No Extra Customs Duties')]"
    product_patanjali_title = "//h1[@class='product_name' and contains(text(),'Mamaearth Onion Shampoo For Hair Fall Care')]"
    ready_to_ship_element_xpath = "//span[text()='Ready to dispatch in 3 - 5 business days']"
    seller_profile_xpath = "//span[text()='Sold By ']/a[text()='Genie India']"
    fulfilled_by_xpath = "//span[text()='Fulfilled By ']/a[text()='Genie India']"
    similar_products_title = "//*[text()='Similar Products']"
    related_products_title = "//*[text()='Related Products']"
    current_product_price_xpath="//*[@class='current_price']/span"
    compare_at_price_product_xpath="//*[@class='was_price']"
    collection_page_discounted_price="//*[@class='snize-discounted-price ']"
    savings_line_xpath="//*[@class='sale savings']"
    copy_right_info_xpath = "//*[@class='copyright_div']"
    #comment
    recently_viewed_products_title = "//h3[text()='Recently viewed products']"
    frequently_bought_together = "//h3[text()='Frequently Bought Together']"
    judgme_badge_xpath = "//*[@class='jdgm-verified-badge__text']"
    trustpilot_review_xpath = "//div[@class='review_icons trustpilot_star']"
    google_review_xpath = "//div[@class='review_icons google_icon']"
    customers_bought_this_also_bought_xpath = "//*[text()='Customers Who Bought This Item Also Bought']"
    customers_bought_this_also_bought_product_xpath = "//*[@class='cbb-also-bought-product-name']/a"
    customers_bought_this_also_bought_variant_xpath = "//*[@class='cbb-also-bought-product-name']/following-sibling::select"  # gives the first variant
    customers_bought_this_also_bought_add_to_cart_xpath = "//*[contains(text(),'Customers Who Bought')]/following-sibling::div/div/ul/li//*[text()='+ Add to cart >']"
    customers_bought_this_also_bought_product_price_xpath = "//*[contains(text(),'Customers Who Bought')]/following-sibling::div/div/ul/li//*[@class='cbb-also-bought-product-price-container']/span/span"
    frequently_bought_together_product_title_xpath = "//*[contains(text(),'Frequently Bought ')]/following-sibling::div/div/ul/li"  # gives all the Frequently bought together products titles
    frequently_bought_together_product_price_xpath = "//*[contains(text(),'Frequently Bought')]/following-sibling::div/div/ul/li//*[@class='ls-price-wrap']/span[contains(@class,'ls-price money')]"
    frequently_bought_together_product_add_to_cart_xpath = "//*[contains(text(),'Frequently Bought')]/following-sibling::div/div/ul/li//*[text()='+ Add to cart']"  # gives all the add to carts butttons for frequently bought together
    frequently_bought_together_product_reviews="//*[contains(text(),'Frequently')]/following-sibling::div/div/ul/li//*[@class='jdgm-prev-badge__text']"
    frequently_bought_together_product_stars="//*[contains(text(),'Frequently')]/following-sibling::div/div/ul/li//*[@class='jdgm-prev-badge__stars']"
    frequently_bought_together_product_questions="//*[contains(text(),'Products')]/following-sibling::div/div/ul/li//*[@class='jdgm-qa-badge__text']"
    frequently_bought_together_product_reviews_all_xpath="//*[contains(text(),'Frequently Bought')]/..//*[@class='ls-title']/..//*[@class='ls-review-wrap']/div"
    similar_products_product_title_xpath = "//*[contains(text(),'Similar')]/following-sibling::div/div/ul/li//*[@class='ls-title']"
    similar_products_product_add_to_cart_xpath = "//*[contains(text(),'Similar')]/following-sibling::div/div/ul/li//*[text()='+ Add to cart']"
    similar_products_product_price_xpath = "//*[contains(text(),'Similar')]/following-sibling::div/div/ul/li//*[@class='ls-price-wrap']/span/following-sibling::span"
    recently_viewed_products_page_product_price = "//*[contains(text(),'Recently')]/following-sibling::div/div/ul/li//*[@class='ls-price-wrap']/span/following-sibling::span"
    recently_viewed_products_page_product_title = "//*[contains(text(),'Recently')]/following-sibling::div/div/ul/li"#get data-attiribute
    recently_viewed_products_page_add_to_cart = "//*[contains(text(),'Recently')]/following-sibling::div/div/ul/li//*[text()='+ Add to cart']"
    recently_viewed_products_page_title = "//h3[text()='Recently Viewed Items']"
    popup_xpath="//*[@class='step_element']"

    # Cart page elements
    cart_quantity_plus_button_xpath = "//div[@class='two-thirds columns medium-down--one-whole cart_content_info cart__item--content']/div/div/span[contains(@class,'product-plus')]"
    cart_plus_button_xpath="//*[@data-func='plus']"
    cart_minus_button_xpath="//*[@data-func='minus']"
    cart_quantity_minus_button_xpath = "//div[@class='two-thirds columns medium-down--one-whole cart_content_info cart__item--content']/div/div/span[contains(@class,'product-minus')]"
    cart_count_xpath = "//div[contains(@class,'header-fixed')]/div[@class='top-bar']/div/div/a[contains(@class,'mini_cart')]/span[@class='cart_count']"
    cart_link_xpath = "//div[@class='cart-user-search']/div/div/a[contains(@class,'mini_cart')]"
    cart_item_price = "//div[@id='shopify-section-cart-template']//div[@class='cart__wrapper is-flex is-flex-wrap']/div/div/div/p[@class='price_total']/span/span"
    cart_max_quantity_msg_xpath = "//div[@class='two-thirds columns medium-down--one-whole cart_content_info cart__item--content']/div/p[contains(@class,'warning')]"
    cart_shipping_info_xpath = "//div[@class='eleven columns omega cart_content_info']/span[@class='delivery_desc']"
    cart_total_shipping_info_xpath = "//span[@class='delivery_desc']"
    cart_page_total_price_xpath = "//div[@class='five columns medium-down--one-whole']/div/div/p/span/span/span[@class='money']"
    cart_item_price_currency_code_xpath = "//div[@class='two-thirds columns medium-down--one-whole cart_content_info cart__item--content']/p[@class='price_total']/span"
    cart_page_total_currency_code_xpath = "//div[@class='one-half column medium-down--one-whole']/div/p/span/span[@class='money']"
    cart_page_remove_button_xpath = "//div[@class='cart-quantity-remove']/div/a"
    cart_page_heading = "//a[text()='My cart']"
    cart_page_breadcrumb_title = "//a[@class='breadcrumbs__link' and text()='My cart']"
    cart_page_breadcrumb_product_title="//a[@class='breadcrumbs__link' and @aria-current='page']"
    cart_input_quantity_xpath="//input[@data-cart-quantity-input='mini-cart']"
    quick_views_xpath = "//button[@class='snize-button snize-action-button snize-quick-view-button']"
    quick_view_product_title_xpath = "//a[@class='snize-quick-view-title']"
    quick_view_add_to_cart_xpath = "//button[@id='snize-quick-view-add-to-cart']"
    quick_view_product_price_xpath = "//div[@class='snize-quick-view-price-wrapper']//*[contains(@class, 'snize-price')]"


    #minicart elements
    minicart_slider = "//div[@class='mini-cart-header']/p[text()='My Cart']"
    minicart_price = "//li/span/span[@class='money']"

    # Checkout page elements
    checkout_button_id = "checkout"
    checkout_page_total_price_xpath = "//tr[@class='total-line']/td/span[contains(@class,'payment-due__price')]"
    checkout_page_currency_xpath = "//tr[@class='total-line']/td/span[contains(@class,'payment-due__currency')]"
    checkout_item_count_xpath = "//span[@class='product-thumbnail__quantity']"
    checkout_item_count_xpath1 = "//*[@class='top-bar--right-menu']//*[@class='icon-bag mini_cart ']//span[@class='cart_count']"
    checkout_breadcrumb_information_xpath="//*[text()='Information']"
    checkout_information_email="//*[@placeholder='Email']"
    checkout_information_phone = "//*[@placeholder='Phone']"
    checkout_information_first_name = "//*[@placeholder='First name']"
    checkout_information_last_name = "//*[@placeholder='Last name']"
    checkout_information_address = "//*[@placeholder='Address']"
    checkout_continue_shipping_button_xpath= "//*[@id='continue_button']"
    # "//div[contains(@data-step, 'contact_information')]//button[@id='continue_button']"
    checkout_continue_payment_button_xpath= "//form[@class='edit_checkout']//div[@class='step__footer']/button[@name='button' and @class='step__footer__continue-btn btn']"
    # "//div[contains(@data-step, 'shipping_method')]//button[@id='continue_button']"
    checkout_shipping_completed="//*[@class='breadcrumb__item breadcrumb__item--completed']//*[text()='Shipping']"
    checkout_payment_credit_card="//input[@aria-describedby='error-for-number tooltip-for-number']"
    checkout_Name_on_the_card="//*[@autocomplete='cc-name']/..//*[@for='name']/following-sibling::input[@placeholder='Name on card']"
    checkout_exp_date="//*[@autocomplete='cc-name']/..//*[@for='name']/following-sibling::input[@id='expiry']"
    checkout_security_code="//*[@autocomplete='cc-name']/..//*[@for='name']/following-sibling::input[@placeholder='Security code']"
    checkout_pay_now_button= "//*[@id='continue_button']"
    # "//div[@class='shown-if-js']//button[@id='continue_button']"
    checkout_card_is_wrong="//*[@class='notice notice--error default-background']"
    checkout_logo="//*[@class='main']/header/a/img[@alt='Distacart']"
    checkout_shipping_fastest_checked_radio_button="//*[contains(text(),'3-5')]/../..//*[@class='input-radio']"

    gift_code_text_box_xpath = "//*[@id='checkout_reduction_code']"
    gift_code_apply_button_xpath = "//button[@name='checkout[submit]']"
    discounted_price_xpath="//*[@class='total-line__price']//span[@class='order-summary__emphasis skeleton-while-loading']" #the second elements of these element will gives you the discounted price 1st element gives the subtotal
    total_price_xpath="//span[@class='payment-due__currency remove-while-loading']//following-sibling::span"
    currency_total_price_checkout_xpath="//*[@class='payment-due__currency remove-while-loading']"
    breadcrumb_to_cart_from_checkout = "//*[text()='Cart']"
    # Product tile elements
    product_tile_thumbnail_xpath = "//div[@class='product-wrap has-secondary-media-swap']/div[@class='relative product_image']/a[contains(@href,'collections')]"
    product_tile_stars_badge_xpath = "//*[@class='stars-container stars-90']"
    product_tile_stars_xpath = "//*[@class='stars-container stars-90']/.."
    product_tile_qa_icon_xpath = "//*[@class='jdgm-qa-badge__icon']"
    product_tile_qa_text_xpath = "//*[@class='snize-questions jdgm-qa-badge__text']"
    product_tile_name = "//h1[@class='product_name']"
    product_tile_reviews_display_xpath = "//*[@class='snize-reviews']"
    product_tile_price_xpath = "//*[@class='snize-price  ']"

    # Related product elements
    related_product_thumbnail_xpath = "//limespot-box[@data-box-type='Related']/div/div/ul/li/a"
    related_product_name_xpath = "//limespot-box[@data-box-type='Related']/div/div/ul/li/a/div/div[@class='ls-title']"
    related_product_stars_badge_xpath = "//limespot-box[@data-box-type='Related']/div/div/ul/li/a/div/div/div/div"
    related_product_stars_xpath = "//limespot-box[@data-box-type='Related']/div/div/ul/li/a/div/div/div/div/span[@class='jdgm-prev-badge__stars']"
    related_product_qa_icon_xpath = "//limespot-box[@data-box-type='Related']/div/div/ul/li/a/div/div/div/div/span[@class='jdgm-qa-badge ']/span[@class='jdgm-qa-badge__icon']"
    related_product_qa_text_xpath = "//limespot-box[@data-box-type='Related']/div/div/ul/li/a/div/div/div/div/span[@class='jdgm-qa-badge ']/span[@class='jdgm-qa-badge__text']"
    related_product_reviews_display_xpath = "//limespot-box[@data-box-type='Related']/div/div/ul/li/a/div/div/div/div/span[@class='jdgm-prev-badge__text']"
    #product_tile_price_xpath = "//section[contains(@class,'datacue-similar')]/div/div/div/ul/li[contains(@class,'tns-slide-active')]/p/span[@class='datacue-rec-current-price']/span/span[@class='money']"
    related_product_price_xpath = "//limespot-box[@data-box-type='Related']/div/div/ul/li/a/div/div/span[@class='ls-price money']"

    # Customer who bought this item also bought elements
    cbb_product_image_xpath = "//ul[@class='cbb-also-bought-slider-list']/li[@class='cbb-also-bought-product']/a/div[@class='cbb-also-bought-product-image']"
    cbb_product_name_xpath = "//ul[@class='cbb-also-bought-slider-list']/li[@class='cbb-also-bought-product']/h3[@class='cbb-also-bought-product-name']/a[contains(@href,'products')]"
    cbb_product_variant_xpath = "//ul[@class='cbb-also-bought-slider-list']/li[@class='cbb-also-bought-product']/select[contains(@class,'variant-select')]"
    cbb_product_price_xpath = "//ul[@class='cbb-also-bought-slider-list']/li[@class='cbb-also-bought-product']/div[@class='cbb-also-bought-product-price-container']/span/span"
    cbb_product_add_to_cart_xpath = "//ul[@class='cbb-also-bought-slider-list']/li[@class='cbb-also-bought-product']/button[@class='cbb-also-bought-add-to-cart-button']/span"
    cbb_product_current_price_xpath = "//ul[@class='cbb-also-bought-slider-list']/li[@class='cbb-also-bought-product']/div[@class='cbb-also-bought-product-price-container']/span/span[@class='money']"
    cbb_section_xpath = "//div[@class='cbb-also-bought-container cbb-desktop-view']"
    cbb_section_title = "//h2[text()='Customers Who Bought This Item Also Bought']"

    # Recommended for you elements
    rec_product_image_xpath = "//section[contains(@class,'datacue-rec-section')]/div/div/div/ul/li/div/a/img"
    rec_product_name_xpath = "//section[contains(@class,'datacue-rec-section')]/div/div/div/ul/li/p/a"
    rec_product_price_xpath = "//section[contains(@class,'datacue-rec-section')]/ul/li/p/span/span[@class='money']"
    rec_product_stars_badge_xpath = "//section[contains(@class,'datacue-rec-section')]/ul/li/div[@class='datacue-rec-product-rating-placeholder']/div/div[contains(@class,'jdgm-prev-badge')]/span[@class='jdgm-prev-badge__stars']"
    rec_product_stars_xpath = "//section[contains(@class,'datacue-rec-section')]/ul/li/div[@class='datacue-rec-product-rating-placeholder']/div/div[contains(@class,'jdgm-prev-badge')]/span[@class='jdgm-prev-badge__text']"
    rec_product_current_price_xpath = "//section[contains(@class,'datacue-rec-section')]/div/div/div/ul/li[@class='datacue-rec tns-item tns-slide-active']/p/span[@class='datacue-rec-current-price']/span"
    recommended_for_you_section_title = "//h3[@class='datacue-rec-title' and text()='Recommended for you']"
    rec_section_add_to_cart = "//button[@name='add to cart' and @data-label='rec-cta']"
    rec_section_view_product ="//a[@class='datacue-rec-add-to-cart-link' and text()='View product']"


    # Recently viewed product elements
    recent_product_thumbnail_xpath = "//div[@id='snize_results']/div[@class='snize-search-results-main-content']/div/ul/li/a"
    recent_product_name_xpath = "//section[contains(@class,'datacue-recent')]/div/div/div/ul/li[contains(@class,'tns-slide-active')]/p/a"
    recent_product_stars_badge_xpath = "//section[contains(@class,'datacue-recent')]/div/div/div/ul/li[contains(@class,'tns-slide-active')]/div/div[contains(@class,'jdgm-widget')]/div/span[@class='jdgm-prev-badge__stars']"
    recent_product_stars_xpath = "//section[contains(@class,'datacue-recent')]/div/div/div/ul/li[contains(@class,'tns-slide-active')]/div/div[contains(@class,'jdgm-widget')]/div/span[@class='jdgm-prev-badge__text']"
    recent_product_qa_icon_xpath = "//section[contains(@class,'datacue-recent')]/div/div/div/ul/li[contains(@class,'tns-slide-active')]/div/div[contains(@class,'jdgm-widget')]/div/span[@class='jdgm-qa-badge ']/span[@class='jdgm-qa-badge__icon']"
    recent_product_qa_text_xpath = "//section[contains(@class,'datacue-recent')]/div/div/div/ul/li[contains(@class,'tns-slide-active')]/div/div[contains(@class,'jdgm-widget')]/div/span[@class='jdgm-qa-badge ']/span[@class='jdgm-qa-badge__text']"
    recent_product_price_xpath = "//section[contains(@class,'datacue-recent')]/div/div/div/ul/li[contains(@class,'tns-slide-active')]/p/span[@class='datacue-rec-current-price']/span[@class='money']"
    recent_product_current_price_xpath = "//section[contains(@class,'datacue-recent')]/div/div/div/ul/li[contains(@class,'tns-slide-active')]/p[@class='datacue-rec-prices']/span/span[@class='money']"

    #In Stock Elements
    in_stock_text_xpath ="//div[contains(text(),'Show in stock only')]"
    in_stock_checkbox_xpath ="//input[@type='checkbox' and @id='show_in_stock_only']"
    no_stock_page_title = "//h2[text()='No products in stock currently in this category']"
    sold_out_xpath = "//div[text()='Sold out']"

    # Seller profile page elements
    seller_profile_xpath = "//div[contains(@class,'mp-store-name')]/span"


    #Trending products
    trending_products_first_one_xpath="//*[@class='limespot-recommendation-box-item ls-review-added']"
    frequently_bought_together_first_one_xpath="//*[@class='ls-image']"

    #Most popular products limespot collection

    first_popular_product_title_xpath = "//li[1][@class='limespot-recommendation-box-item ls-review-added']/a/div/div[@class='ls-title']"
    first_popular_product_price = "//div[@class='ls-price-wrap']/span[@style='margin-right: 5px;']"
    first_popular_product_add_to_cart = "//li[1][@class='limespot-recommendation-box-item ls-review-added']//div/div[@class='ls-add-to-cart-wrap']/button"
    first_popular_product_add_to_cart_popup_xpath = "//div[@class='ls-select__options']/button[1][@class='ls-select__option ls-add-to-cart']"


    #Google Xpaths
    carousal_distacart="//*[text()='Distacart']"
    google_search_bar="//*[@action='/search']//input"



    #Shipping text box elements
    shipping_box_xpath = "//div[@id='shipping_info_div']"
    shipping_info_header = "//div/b[text()='Shipping Information']"
    #Shipping info for USD
    shipping_details_xpath_USD  = "//p[@id='shipping_dtl']/b[contains(text(),'Free standard shipping')]/../b[contains(text(),'$35.00 USD')]"
    shipping_delay_xpath_USD = "//p[text()='You may expect a delay in delivery (5-7 business days) due to COVID.']"
    product_page_sslsecure_xpath = "//*[@class=' trustSeals_productpage ']//*[@class='cc-vp-wrap']//span[text()='SSL Secure ']"
    product_page_Authentic_xpath = "//*[@class=' trustSeals_productpage ']//*[@class='cc-vp-wrap']//span[text()='Authentic ']"
    product_page_Guaranteed_xpath = "//*[@class=' trustSeals_productpage ']//*[@class='cc-vp-wrap']//span[text()='Guaranteed ']"
    product_page_easy_xpath = "//*[@class=' trustSeals_productpage ']//*[@class='cc-vp-wrap']//span[text()='easy ']"
    #Mini cart trust seals
    mini_cart_trust_seals_xpath = "//*[@class='trustSeals_minicart']"
    minicart_secure_xpath = "//*[@class='trustSeals_minicart']/*[@class='valueProp']//span[text()='SSL Secure ']"
    minicart_authentic_xpath = "//*[@class='trustSeals_minicart']/*[@class='valueProp']//span[text()='Authentic ']"
    minicart_guaranteed_xpath = "//*[@class='trustSeals_minicart']/*[@class='valueProp']//span[text()='Guaranteed ']"
    #CheckoutPage trust seals
    checkoutPage_fast_shipping_xpath = "//div[@class='desktop-widget']//*[text()='Fast shipping']"
    checkoutPage_safe_checkout_xpath = "//div[@class='desktop-widget']//*[text()='SAFE CHECKOUT']"
    checkoutPage_customer_support_xpath = "//div[@class='desktop-widget']//*[text()='Customer Support']"
    checkoutPage_no_custom_duties_xpath = "//div[@class='desktop-widget']//*[text()='No custom duties']"
    # product_authentic_xpath = "//*[@class='cc-vp-br']/following-sibling::span[text()='Authentic ']"
    # product_secure_xpath = "//*[@class='cc-vp-br']/following-sibling::span[text()='SSL Secure ']"
    # product_guaranteed_xpath = "//*[@class='cc-vp-br']/following-sibling::span[text()='Guaranteed ']"
    # product_easy_returns_xpath="//*[@class='cc-vp-br']/following-sibling::span[text()='easy ']"
    shipping_custom_duties_xpath_USD = "//div[text()='100% Satisfaction Guaranteed']"
    #Shipping info for AUD
    shipping_details_xpath_AUD = "//p[text()='Free Express shipping on orders of $68.99 AUD or more']"
    #Shipping info for CAD
    shipping_details_xpath_CAD = "//p[text()='Free Express shipping to all over  Canada  on orders of $65 CAD or more']"
    #Shipping info for CHF
    shipping_details_xpath_CHF = "//p[text()='  Free express shipping to  Switzerland  on orders over SFr. 47 or more']"
    # Shipping info for EUR
    shipping_details_xpath_EUR = "//p[text()='Free Express shipping to all over European Countries on orders of €44 or more']"
    # Shipping info for GBP
    shipping_details_xpath_GBP = "//p[text()='Free shipping to all over  United Kingdom  on orders of £50 or more']"
    # Shipping info for INR
    shipping_details_xpath_INR = "//p[text()='Free shipping from India to USA, Canada, Netherlands and UK on Orders of Rs. 3000 or more']"
    #Shipping info for SGD
    shipping_details_xpath_SGD = "//p[text()='Free Express shipping to all over  Singapore on orders of $67.30 SGD or more']"
    #Shipping info for MXN
    shipping_details_xpath_MXN = "//p[text()='Free Express shipping to all over  Mexico on orders of $998 MXN or more']"
    #patanjali product page elements
    patanjali_giloy_product_page_element = "//div/span/a/span[text()='Home']/../../../span/a/span[text()='Products']/../../../span/a/span[text()='Patanjali Giloy Ghanvati (40 GM)']"

    #Recently Viewed Elements
    recently_viewed_section = "//*[text()='Recently Viewed Items']"
    recently_viewed_product_element = "//div[text()='Patanjali Divya Coronil Kit - Coronil Tablet, Anu Taila, Swasari Vati']/../../../../../../../../limespot-box/h3[text()='Recently Viewed Items']"

    #cart_slider_express_checkout_elements
    shoppay_element = "//div[@role='button' and @data-testid='ShopifyPay-button']"
    googlepay_element ="//div[@role='button' and @data-testid='GooglePay-button']"
    shoppay_checkout_page_element= "//h2[text()='Quick checkout']"
    quick_checkout_element = "//h3[text()='Order summary']"

    #add_to_cart_elements
    ayurvedic_random_product_element = "//div[@class='product-details']/span"
    add_to_cart_button_card = "//div[@class='collection_addtocart']/button[text()='Add to Cart']/../../../../../div[@class='product-details']/span[text()='{}']"

    # Blog page elements
    blog_next_button_xpath = "//span[@class='next']/a"
    blog_prev_button_xpath = "//span[@class='prev']/a"
    blog_read_more_button_xpath = "//a[contains(@class,'read-more-button')]"
    blog_pages_xpath = "//*[@class='container']//*[@class='image-element__wrap']"
    blog_related_products_title_xpath = "//*[@id='related_products_slider']//*[@class='pb-text-title']"
    blog_related_products = "//*[text()='Related Products']"
    blog_related_products_price_xpath = "//*[@id='related_products_slider']//*[@class='pb-text-title']/following-sibling::div/following-sibling::div/following-sibling::div"
    blog_related_products_add_to_cart = "//*[@class='btn']"
    blog_new_arrivals_xpath = "//*[text()='New Arrivals']"
    blog_trending_xpath = "//*[text()='Trending Items']"
    blog_trending_section_add_to_cart_xpath = "//*[contains(text(),'Items')]/following-sibling::div/div/ul/li//*[text()='+ Add to cart']"
    blog_trending_section_product_variants_xpath = "//*[@class='ls-select__text']"
    blog_trending_section_product_title_xpath = "//*[contains(text(),'Items')]/following-sibling::div/div/ul/li//*[@class='ls-title']"
    blog_trending_section_product_price_xpath = "//*[contains(text(),'Items')]/following-sibling::div/div/ul/li//*[@class='ls-price-wrap']/span/following-sibling::span"
    blog_new_arrivals_section_add_to_cart_xpath = "//*[contains(text(),'New')]/following-sibling::div/div/ul/li//*[text()='+ Add to cart']"
    blog_new_arrivals_section_product_variants_xpath = "//*[@class='ls-select__text']"
    blog_new_arrivals_section_product_title_xpath = "//*[contains(text(),'New')]/following-sibling::div/div/ul/li//*[@class='ls-title']"
    blog_new_arrivals_section_product_price_xpath = "//*[contains(text(),'New')]/following-sibling::div/div/ul/li//*[@class='ls-price-wrap']/span/following-sibling::span"

    #shipping page elements
    shipping_page_title = "//a[@class='breadcrumbs__link' and text()='Shipping']"
    shipping_page_header_text = " //div[@class='text-header']/p[text()='Express Shipping To: ' ]"

    #Copyright policy page elements
    copyright_page_title = "//a[@class='breadcrumbs__link' and text()='Copyright Policy']"
    copyright_page_text = "//p[contains(text(),'Distacart Inc 2022. All rights reserved. No content from this website (including text, images, videos) may be copied, plagiarised or used in any form without the explicit consent of Distacart Inc.')]"

    #Report Infringement page elements
    report_infringement_title="//a[text()='Report Infringement']"
    send_message_button = "//input[@value='Send Message']"

    #Read More text
    read_more_text = "//a[@id='btn-read__more' and text()='Read more']"

    #anchor text elements
    footer_user_text = "//p[@class='heading-footer' and text()='User']"
    personal_info_footer_text = "//a[text()='Personal info']"
    orders_footer_text = "//a[text()='Orders']"
    addresses_footer_text = "//a[text()='Addresses']"
    personal_info_page_element = "//a[text()='Account']"
    customer_login_element = "//h1[text()='Customer Login']"
    copyright_policy_element = "//a[text()='Copyright Policy']"

    #blog page elements
    related_products_blog = "//div[@id='related_products_header']/h4[text()='Related Products']"
    related_products_tile = "//h4/a[contains(text(),'Me Kavachh Ayurvedic Immunity Drops')]"

    #Customer Reviews Section
    customer_reviews_section = "//h2[text()='Customer Reviews']"

    #Cart Slider View Full cart Link
    view_full_cart_link = "//p[@class='view-full-cart']/a[text()='View Full Cart']"


    #Search result elements
    search_add_to_cart = "//span[text()='{}']/..//button[contains(text(),'Quick view')]"
    search_quick_view="//*[@id='snize-search-results-grid-mode']/ul/li//*[text()='{}']/..//*[text()='Quick view']"
    search_product_price_format_xpath="//*[@id='snize-search-results-grid-mode']/ul/li//*[text()='{}']/..//*[@class='snize-price-list']/span"
    search_product = "//span[text()='{}']"
    search_add_to_cart1 = "//button[@class=' ajax-submit action_button add_to_cart  action_button--secondary   product_add_to_cart product_add_to_cart1']"
    search_view_cart = "//span[text()='{}']/..//button[contains(text(),'View cart')]"
    search_variant_drop_box="//*[@id='snize-option-selector-1']"
    search_variant_drop_box_option="//*[@id='snize-option-selector-1']/option[{}]"
    search_view_full_cart = "//*[text()='View Full Cart']"
    search_sold_out = "//span[text()='{}']/..//button[contains(text(),'Sold out')]"
    search_empty = "//div[@class='snize-no-products-found-text']//*[contains(text(),'Nothing found')]"
    search_instock_filter_chkbox = "//div[@class='snize-filters-sidebar snize-product-filters']//li[@class='snize-filter-checked snize-disabled']/label/div/span"
    search_text_box_xpath = "//*[@class='main-nav__wrapper']//*[@class='search__form']//*[@type='text']"
    search_product_title = "//span[@class='snize-title']"
    search_product_img="//*[@class='snize-four-columns']/ul/li//*[@class='snize-title']/../../div/span/img"
    search_product_price = "//*[@class='snize-four-columns']/ul/li//*[@class='snize-price-list']/span"
    search_product_quick_view = "//*[@class='snize-four-columns']/ul/li//*[text()='+   Add to Cart']"
    search_product_add_to_cart = "//*[@id='snize-quick-view-add-to-cart']"
    search_product_view_cart = "//*[@id='snize-quick-view-view-cart']"

    after_pay_price = "//afterpay-placement"
    sms_offer_left_item = "//div[contains(@class,'sms-offer')]/div/div/p"
    sms_offer_right_item = "//div[@class='one-half column medium-down--one-whole right-section-deal']/p"
    email_offer_item = "//div[contains(@class,'three-eighths')]/h2"

    #Subscription elements
    subscription_purchase_option = "//div[text()='Purchase Options']"
    onetime_purchase_text = "//span[text()='One Time Purchase']"
    subscribe_and_save_radio_button = "//div[@class='appstle_subscription_radio_wrapper']/input[@id='appstle_selling_plan_label_20']/../label/span/span[@class='appstle_dot']"
    subscribe_and_save_text = "//span[text()='Subscribe and save 7%(Cancel anytime)']"
    subscribe_and_save_selected_text = "//div[@class='appstle_subscription_wrapper_option appstle_include_dropdown appstle_selected_background']//span/../span[text()='Subscribe and save 5%']"
    deliver_frequency_text = "//div[@class='appstle_subscribe_option']/label[text()='DELIVERY FREQUENCY']"
    brand_and_brand_partners_xpath = "//div[@class='logo-bar__item']/a/div/img"
    home_products_css = "span[class='snize-overhidden']"
    collection_product_name_css = "span[class='snize-overhidden'] span[class='snize-title']"
    collection_product_price_css = "span[class='snize-overhidden'] div[class='snize-price-list'] span[class*='snize-price']"
    sticky_cart_increase_quantity_xpath = "//div[@class='left product-quantity-box prod_qty_box_mobile']//span[@class='ss-icon product-plus js-change-quantity']//span//*[name()='svg']"
    sticky_cart_decrease_quantity_xpath = "//div[contains(@class,'left product-quantity-box prod_qty_box_mobile')]//span[contains(@class,'ss-icon product-minus js-change-quantity')]//span//*[name()='svg']"
    sticky_add_cart_xpath = "//div[@class=' purchase-details-product-addbtn ']//button"
    sticky_quantity_input_xpath = "//input[@name='quantity']"
    sticky_add_cart_product_price_xpath = "//div[@class='current_price_div']//span[@class='current_price']//span[@class='money']"
    mini_cart_delete_xpath = "//span[@class='remove-icon']//*[name()='svg']"

    #shipping box

    shipping_box_title = "//div[@class='shipping_rates'] /div[contains(text(),'United States shipping price')]"
    shipping_rates_table_xpath = "//div[@class='shipping_rates']//table/tbody/tr[1]"
    shipping_rate_US_slab1 = "//tr/td[text()='Cart Value (USD)']/../td[text()='>= $35']/../../tr/td[text()='Shipping Rates (USD)']/../td/span[text()='FREE']"
    shipping_rate_US_slab2 = "//tr/td[text()='Cart Value (USD)']/../td[text()='$25-$34.99']/../../tr/td[text()='Shipping Rates (USD)']/../td[text()='$4.97']"
    shipping_rate_US_slab3 = "//tr/td[text()='Cart Value (USD)']/../td[text()='$15-$24.99']/../../tr/td[text()='Shipping Rates (USD)']/../td[text()='$6.97']"
    shipping_rate_US_slab4 = "//tr/td[text()='Cart Value (USD)']/../td[text()='<= $14.99']/../../tr/td[text()='Shipping Rates (USD)']/../td[text()='$11.97']"
    # shipping_rates_US_slab1 = "//tr/td[text()='Cart Value (USD)']/../td[text()='>= $59']/../../tr/td[text()='Shipping Rates (USD)']/../td/span[text()='FREE']"
    # shipping_rate_US_slab2 = "//tr/td[text()='Cart Value (USD)']/../td[text()='$49-$58.99']/../../tr/td[text()='Shipping Rates (USD)']/../td[text()='$1.97']"
    # shipping_rate_US_slab3 = "//tr/td[text()='Cart Value (USD)']/../td[text()='$35-$48.99']/../../tr/td[text()='Shipping Rates (USD)']/../td[text()='$5.97']"
    # shipping_rate_US_slab4 = "//tr/td[text()='Cart Value (USD)']/../td[text()='$25-$34.99']/../../tr/td[text()='Shipping Rates (USD)']/../td[text()='$8.97']"
    # shipping_rate_US_slab5 = "//tr/td[text()='Cart Value (USD)']/../td[text()='$15-$24.99']/../../tr/td[text()='Shipping Rates (USD)']/../td[text()='$11.97']"
    # shipping_rate_US_slab6 = "//tr/td[text()='Cart Value (USD)']/../td[text()='$10-$14.99']/../../tr/td[text()='Shipping Rates (USD)']/../td[text()='$15.97']"
    # shipping_rate_US_slab7 = "//tr/td[text()='Cart Value (USD)']/../td[text()='<= $9.99']/../../tr/td[text()='Shipping Rates (USD)']/../td[text()='$18.97']"
